# numpy with EDA

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np


a = np.array([1,2,3])
b=[1,2,3]
a
b

[1, 2, 3]

In [35]:
b = np.array([(3.5,2,3), (4,5,6)], dtype = float)
b

array([[3.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
a.shape #Array dimensions
b.shape
len(b)#Length of array
b.ndim
b.size

6

In [21]:
b.dtype
b.dtype.name
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:

print(a)
print(b)
c=a+b
c

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [31]:
x=a * b
x
np.multiply(a,b)
np.square(b)

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [36]:
 b.sort() #Sort an array
b

array([[2. , 3. , 3.5],
       [4. , 5. , 6. ]])